name: geog0133_env

channels:
  - conda-forge
dependencies:
  - python>=3.6
  - gdal>=2.3.0
  - libgdal>=2.3.0
  - matplotlib
  - ipykernel
  - fiona
  - scipy
  - pandas
  - xlrd
  - nbconvert
  - git-lfs
  - jupyter
  - pyephem
  - numpy
  - ipywidgets
  - requests
  - nbpresent
  - jupyter_contrib_nbextensions
